# Form implementation generated from reading ui file 'UI_Reply.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from common import get_resource_path


class Ui_ReplyDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("ReplyDialog")
        Dialog.resize(862, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(245, 249, 254);\n"
"border-radius:25px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setStyleSheet(".QWidget{\n"
"background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                  stop:0 rgb(105, 27, 253), \n"
"                                  stop:1 rgb(200, 160, 240));\n"
"border-radius:16px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(18, 18, 18, 18)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_title = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgba(222, 255, 255, 255)")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_5.addWidget(self.label_title)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_3)
        self.scrollArea.setStyleSheet("border: none;\n"
"background:rgba(0, 0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 784, 312))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_7.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_7.setStyleSheet("border-radius: 8px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalFrame_7)
        self.horizontalLayout_12.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.RuleName_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit.setFont(font)
        self.RuleName_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit.setObjectName("RuleName_lineEdit")
        self.horizontalLayout_12.addWidget(self.RuleName_lineEdit)
        self.label = QtWidgets.QLabel(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.KeyWord_comboBox = QtWidgets.QComboBox(parent=self.horizontalFrame_7)
        self.KeyWord_comboBox.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox.setFont(font)
        self.KeyWord_comboBox.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox.setObjectName("KeyWord_comboBox")
        self.KeyWord_comboBox.addItem("")
        self.KeyWord_comboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.KeyWord_comboBox)
        self.KeyWord_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_7)
        self.KeyWord_lineEdit.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit.setFont(font)
        self.KeyWord_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit.setObjectName("KeyWord_lineEdit")
        self.horizontalLayout_12.addWidget(self.KeyWord_lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.Reply_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_7)
        self.Reply_lineEdit.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit.setFont(font)
        self.Reply_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit.setObjectName("Reply_lineEdit")
        self.horizontalLayout_12.addWidget(self.Reply_lineEdit)
        self.file_pushButton = QtWidgets.QPushButton(parent=self.horizontalFrame_7)
        self.file_pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton.setIcon(icon)
        self.file_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton.setObjectName("file_pushButton")
        self.horizontalLayout_12.addWidget(self.file_pushButton)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(4, 1)
        self.horizontalLayout_12.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_7)
        self.horizontalFrame_8 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_8.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_8.setStyleSheet("border-radius: 8px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_13.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.RuleName_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_2.setFont(font)
        self.RuleName_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_2.setObjectName("RuleName_lineEdit_2")
        self.horizontalLayout_13.addWidget(self.RuleName_lineEdit_2)
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.KeyWord_comboBox_2 = QtWidgets.QComboBox(parent=self.horizontalFrame_8)
        self.KeyWord_comboBox_2.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_2.setFont(font)
        self.KeyWord_comboBox_2.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_2.setObjectName("KeyWord_comboBox_2")
        self.KeyWord_comboBox_2.addItem("")
        self.KeyWord_comboBox_2.addItem("")
        self.horizontalLayout_13.addWidget(self.KeyWord_comboBox_2)
        self.KeyWord_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_8)
        self.KeyWord_lineEdit_2.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_2.setFont(font)
        self.KeyWord_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_2.setObjectName("KeyWord_lineEdit_2")
        self.horizontalLayout_13.addWidget(self.KeyWord_lineEdit_2)
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.Reply_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_8)
        self.Reply_lineEdit_2.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_2.setFont(font)
        self.Reply_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_2.setObjectName("Reply_lineEdit_2")
        self.horizontalLayout_13.addWidget(self.Reply_lineEdit_2)
        self.file_pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalFrame_8)
        self.file_pushButton_2.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_2.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_2.setIcon(icon)
        self.file_pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_2.setObjectName("file_pushButton_2")
        self.horizontalLayout_13.addWidget(self.file_pushButton_2)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(4, 1)
        self.horizontalLayout_13.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_8)
        self.horizontalFrame_9 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_9.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_9.setStyleSheet("border-radius: 8px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_14.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(parent=self.horizontalFrame_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.RuleName_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_3.setFont(font)
        self.RuleName_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_3.setObjectName("RuleName_lineEdit_3")
        self.horizontalLayout_14.addWidget(self.RuleName_lineEdit_3)
        self.label_5 = QtWidgets.QLabel(parent=self.horizontalFrame_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.KeyWord_comboBox_3 = QtWidgets.QComboBox(parent=self.horizontalFrame_9)
        self.KeyWord_comboBox_3.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_3.setFont(font)
        self.KeyWord_comboBox_3.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_3.setObjectName("KeyWord_comboBox_3")
        self.KeyWord_comboBox_3.addItem("")
        self.KeyWord_comboBox_3.addItem("")
        self.horizontalLayout_14.addWidget(self.KeyWord_comboBox_3)
        self.KeyWord_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_9)
        self.KeyWord_lineEdit_3.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_3.setFont(font)
        self.KeyWord_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_3.setObjectName("KeyWord_lineEdit_3")
        self.horizontalLayout_14.addWidget(self.KeyWord_lineEdit_3)
        self.label_6 = QtWidgets.QLabel(parent=self.horizontalFrame_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.Reply_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_9)
        self.Reply_lineEdit_3.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_3.setFont(font)
        self.Reply_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_3.setObjectName("Reply_lineEdit_3")
        self.horizontalLayout_14.addWidget(self.Reply_lineEdit_3)
        self.file_pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalFrame_9)
        self.file_pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_3.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_3.setIcon(icon)
        self.file_pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_3.setObjectName("file_pushButton_3")
        self.horizontalLayout_14.addWidget(self.file_pushButton_3)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(4, 1)
        self.horizontalLayout_14.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_9)
        self.horizontalFrame_10 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_10.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_10.setStyleSheet("border-radius: 8px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_10.setObjectName("horizontalFrame_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalFrame_10)
        self.horizontalLayout_15.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalFrame_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.RuleName_lineEdit_4 = QtWidgets.QLineEdit(parent=self.horizontalFrame_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_4.setFont(font)
        self.RuleName_lineEdit_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_4.setObjectName("RuleName_lineEdit_4")
        self.horizontalLayout_15.addWidget(self.RuleName_lineEdit_4)
        self.label_7 = QtWidgets.QLabel(parent=self.horizontalFrame_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.KeyWord_comboBox_4 = QtWidgets.QComboBox(parent=self.horizontalFrame_10)
        self.KeyWord_comboBox_4.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_4.setFont(font)
        self.KeyWord_comboBox_4.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_4.setObjectName("KeyWord_comboBox_4")
        self.KeyWord_comboBox_4.addItem("")
        self.KeyWord_comboBox_4.addItem("")
        self.horizontalLayout_15.addWidget(self.KeyWord_comboBox_4)
        self.KeyWord_lineEdit_4 = QtWidgets.QLineEdit(parent=self.horizontalFrame_10)
        self.KeyWord_lineEdit_4.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_4.setFont(font)
        self.KeyWord_lineEdit_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_4.setObjectName("KeyWord_lineEdit_4")
        self.horizontalLayout_15.addWidget(self.KeyWord_lineEdit_4)
        self.label_8 = QtWidgets.QLabel(parent=self.horizontalFrame_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.Reply_lineEdit_4 = QtWidgets.QLineEdit(parent=self.horizontalFrame_10)
        self.Reply_lineEdit_4.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_4.setFont(font)
        self.Reply_lineEdit_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_4.setObjectName("Reply_lineEdit_4")
        self.horizontalLayout_15.addWidget(self.Reply_lineEdit_4)
        self.file_pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalFrame_10)
        self.file_pushButton_4.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_4.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_4.setIcon(icon)
        self.file_pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_4.setObjectName("file_pushButton_4")
        self.horizontalLayout_15.addWidget(self.file_pushButton_4)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(4, 1)
        self.horizontalLayout_15.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_10)
        self.horizontalFrame_11 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_11.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_11.setStyleSheet("border-radius: 8px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_11.setObjectName("horizontalFrame_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalFrame_11)
        self.horizontalLayout_16.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(parent=self.horizontalFrame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.RuleName_lineEdit_5 = QtWidgets.QLineEdit(parent=self.horizontalFrame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_5.setFont(font)
        self.RuleName_lineEdit_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_5.setObjectName("RuleName_lineEdit_5")
        self.horizontalLayout_16.addWidget(self.RuleName_lineEdit_5)
        self.label_14 = QtWidgets.QLabel(parent=self.horizontalFrame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.KeyWord_comboBox_5 = QtWidgets.QComboBox(parent=self.horizontalFrame_11)
        self.KeyWord_comboBox_5.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_5.setFont(font)
        self.KeyWord_comboBox_5.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_5.setObjectName("KeyWord_comboBox_5")
        self.KeyWord_comboBox_5.addItem("")
        self.KeyWord_comboBox_5.addItem("")
        self.horizontalLayout_16.addWidget(self.KeyWord_comboBox_5)
        self.KeyWord_lineEdit_5 = QtWidgets.QLineEdit(parent=self.horizontalFrame_11)
        self.KeyWord_lineEdit_5.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_5.setFont(font)
        self.KeyWord_lineEdit_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_5.setObjectName("KeyWord_lineEdit_5")
        self.horizontalLayout_16.addWidget(self.KeyWord_lineEdit_5)
        self.label_15 = QtWidgets.QLabel(parent=self.horizontalFrame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.Reply_lineEdit_5 = QtWidgets.QLineEdit(parent=self.horizontalFrame_11)
        self.Reply_lineEdit_5.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_5.setFont(font)
        self.Reply_lineEdit_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_5.setObjectName("Reply_lineEdit_5")
        self.horizontalLayout_16.addWidget(self.Reply_lineEdit_5)
        self.file_pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalFrame_11)
        self.file_pushButton_5.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_5.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_5.setIcon(icon)
        self.file_pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_5.setObjectName("file_pushButton_5")
        self.horizontalLayout_16.addWidget(self.file_pushButton_5)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(4, 1)
        self.horizontalLayout_16.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_download = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_download.setMinimumSize(QtCore.QSize(88, 36))
        self.pushButton_download.setMaximumSize(QtCore.QSize(88, 36))
        self.pushButton_download.setStyleSheet("QPushButton {\n"
"    background-color: rgba(105, 27, 253, 180);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(105, 27, 253, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 27, 253, 250);\n"
"}")
        self.pushButton_download.setObjectName("pushButton_download")
        self.horizontalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 5)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.setStretch(0, 5)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_6.setStretch(0, 9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "自动回复规则"))
        self.label_9.setText(_translate("Dialog", "规则名称"))
        self.RuleName_lineEdit.setPlaceholderText(_translate("Dialog", "输入名称"))
        self.label.setText(_translate("Dialog", "关键词"))
        self.KeyWord_comboBox.setItemText(0, _translate("Dialog", "半匹配"))
        self.KeyWord_comboBox.setItemText(1, _translate("Dialog", "全匹配"))
        self.KeyWord_lineEdit.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_2.setText(_translate("Dialog", "回复内容"))
        self.Reply_lineEdit.setPlaceholderText(_translate("Dialog", "文字或文件路径"))
        self.label_10.setText(_translate("Dialog", "规则名称"))
        self.RuleName_lineEdit_2.setPlaceholderText(_translate("Dialog", "输入名称"))
        self.label_3.setText(_translate("Dialog", "关键词"))
        self.KeyWord_comboBox_2.setItemText(0, _translate("Dialog", "半匹配"))
        self.KeyWord_comboBox_2.setItemText(1, _translate("Dialog", "全匹配"))
        self.KeyWord_lineEdit_2.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_4.setText(_translate("Dialog", "回复内容"))
        self.Reply_lineEdit_2.setPlaceholderText(_translate("Dialog", "文字或文件路径"))
        self.label_11.setText(_translate("Dialog", "规则名称"))
        self.RuleName_lineEdit_3.setPlaceholderText(_translate("Dialog", "输入名称"))
        self.label_5.setText(_translate("Dialog", "关键词"))
        self.KeyWord_comboBox_3.setItemText(0, _translate("Dialog", "半匹配"))
        self.KeyWord_comboBox_3.setItemText(1, _translate("Dialog", "全匹配"))
        self.KeyWord_lineEdit_3.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_6.setText(_translate("Dialog", "回复内容"))
        self.Reply_lineEdit_3.setPlaceholderText(_translate("Dialog", "文字或文件路径"))
        self.label_12.setText(_translate("Dialog", "规则名称"))
        self.RuleName_lineEdit_4.setPlaceholderText(_translate("Dialog", "输入名称"))
        self.label_7.setText(_translate("Dialog", "关键词"))
        self.KeyWord_comboBox_4.setItemText(0, _translate("Dialog", "半匹配"))
        self.KeyWord_comboBox_4.setItemText(1, _translate("Dialog", "全匹配"))
        self.KeyWord_lineEdit_4.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_8.setText(_translate("Dialog", "回复内容"))
        self.Reply_lineEdit_4.setPlaceholderText(_translate("Dialog", "文字或文件路径"))
        self.label_13.setText(_translate("Dialog", "规则名称"))
        self.RuleName_lineEdit_5.setPlaceholderText(_translate("Dialog", "输入名称"))
        self.label_14.setText(_translate("Dialog", "关键词"))
        self.KeyWord_comboBox_5.setItemText(0, _translate("Dialog", "半匹配"))
        self.KeyWord_comboBox_5.setItemText(1, _translate("Dialog", "全匹配"))
        self.KeyWord_lineEdit_5.setPlaceholderText(_translate("Dialog", "输入关键词"))
        self.label_15.setText(_translate("Dialog", "回复内容"))
        self.Reply_lineEdit_5.setPlaceholderText(_translate("Dialog", "文字或文件路径"))
        self.pushButton_download.setText(_translate("Dialog", "保存"))
