# Form implementation generated from reading ui file 'UI_Reply.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from common import get_resource_path


class Ui_ReplyDialog(object):
    def setupUi(self, ReplyDialog):
        ReplyDialog.setObjectName("ReplyDialog")
        ReplyDialog.resize(862, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReplyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=ReplyDialog)
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgba(170, 0, 255, 15);\n"
"border-radius:36px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setStyleSheet(".QWidget{\n"
"background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                  stop:0 rgb(105, 27, 253), \n"
"                                  stop:1 rgb(200, 160, 240));\n"
"border-radius:27px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(18, 12, 12, 12)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_title = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgba(222, 255, 255, 255)")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_5.addWidget(self.label_title)
        self.mainframe = QtWidgets.QFrame(parent=self.widget_3)
        self.mainframe.setStyleSheet("background:rgba(255, 255, 255, 80);\n"
"border-radius: 15px;")
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainframe)
        self.scrollArea.setStyleSheet("QScrollArea, QScrollArea * {\n"
"    border: none;\n"
"    background: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QScrollArea QScrollBar:vertical {\n"
"    width: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical {\n"
"    background: rgba(125, 125, 125, 20%);\n"
"    border-radius: 4px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical:hover {\n"
"    background: rgba(125, 125, 125, 70%);\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-line:vertical,\n"
"QScrollArea QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-page:vertical,\n"
"QScrollArea QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"    border-radius: 4px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 352))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(4, 6, 4, 0)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_12.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_12.setStyleSheet("border-radius: 9px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_12.setObjectName("horizontalFrame_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalFrame_12)
        self.horizontalLayout_17.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.RuleName_lineEdit_1 = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_1.setFont(font)
        self.RuleName_lineEdit_1.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_1.setObjectName("RuleName_lineEdit_1")
        self.horizontalLayout_17.addWidget(self.RuleName_lineEdit_1)
        self.label_17 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.KeyWord_comboBox_1 = QtWidgets.QComboBox(parent=self.horizontalFrame_12)
        self.KeyWord_comboBox_1.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_1.setFont(font)
        self.KeyWord_comboBox_1.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_1.setObjectName("KeyWord_comboBox_1")
        self.KeyWord_comboBox_1.addItem("")
        self.KeyWord_comboBox_1.addItem("")
        self.horizontalLayout_17.addWidget(self.KeyWord_comboBox_1)
        self.KeyWord_lineEdit_1 = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        self.KeyWord_lineEdit_1.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_1.setFont(font)
        self.KeyWord_lineEdit_1.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_1.setObjectName("KeyWord_lineEdit_1")
        self.horizontalLayout_17.addWidget(self.KeyWord_lineEdit_1)
        self.label_18 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.Reply_lineEdit_1 = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        self.Reply_lineEdit_1.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_1.setFont(font)
        self.Reply_lineEdit_1.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_1.setObjectName("Reply_lineEdit_1")
        self.horizontalLayout_17.addWidget(self.Reply_lineEdit_1)
        self.file_pushButton_1 = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.file_pushButton_1.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_1.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_1.setIcon(icon)
        self.file_pushButton_1.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_1.setObjectName("file_pushButton_1")
        self.horizontalLayout_17.addWidget(self.file_pushButton_1)
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.pushButton_1.setMinimumSize(QtCore.QSize(42, 24))
        self.pushButton_1.setMaximumSize(QtCore.QSize(42, 24))
        self.pushButton_1.setStyleSheet("            QPushButton {\n"
"                background-color: rgba(255, 0, 0, 0.55);\n"
"                border: none;\n"
"                border-radius: 4px;\n"
"                color: white;\n"
"                font-size: 12px;\n"
"                padding: 2px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 0, 0, 0.75);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgba(255, 0, 0, 0.95);\n"
"            }")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_17.addWidget(self.pushButton_1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.horizontalLayout_17.setStretch(4, 1)
        self.horizontalLayout_17.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_12)
        self.horizontalFrame_13 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_13.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_13.setStyleSheet("border-radius: 9px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_13.setObjectName("horizontalFrame_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalFrame_13)
        self.horizontalLayout_18.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(parent=self.horizontalFrame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.RuleName_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_2.setFont(font)
        self.RuleName_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_2.setObjectName("RuleName_lineEdit_2")
        self.horizontalLayout_18.addWidget(self.RuleName_lineEdit_2)
        self.label_20 = QtWidgets.QLabel(parent=self.horizontalFrame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.KeyWord_comboBox_2 = QtWidgets.QComboBox(parent=self.horizontalFrame_13)
        self.KeyWord_comboBox_2.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_2.setFont(font)
        self.KeyWord_comboBox_2.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_2.setObjectName("KeyWord_comboBox_2")
        self.KeyWord_comboBox_2.addItem("")
        self.KeyWord_comboBox_2.addItem("")
        self.horizontalLayout_18.addWidget(self.KeyWord_comboBox_2)
        self.KeyWord_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_13)
        self.KeyWord_lineEdit_2.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_2.setFont(font)
        self.KeyWord_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_2.setObjectName("KeyWord_lineEdit_2")
        self.horizontalLayout_18.addWidget(self.KeyWord_lineEdit_2)
        self.label_21 = QtWidgets.QLabel(parent=self.horizontalFrame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.Reply_lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalFrame_13)
        self.Reply_lineEdit_2.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_2.setFont(font)
        self.Reply_lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_2.setObjectName("Reply_lineEdit_2")
        self.horizontalLayout_18.addWidget(self.Reply_lineEdit_2)
        self.file_pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalFrame_13)
        self.file_pushButton_2.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_2.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_2.setIcon(icon)
        self.file_pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_2.setObjectName("file_pushButton_2")
        self.horizontalLayout_18.addWidget(self.file_pushButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalFrame_13)
        self.pushButton_2.setMinimumSize(QtCore.QSize(42, 24))
        self.pushButton_2.setMaximumSize(QtCore.QSize(42, 24))
        self.pushButton_2.setStyleSheet("            QPushButton {\n"
"                background-color: rgba(255, 0, 0, 0.55);\n"
"                border: none;\n"
"                border-radius: 4px;\n"
"                color: white;\n"
"                font-size: 12px;\n"
"                padding: 2px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 0, 0, 0.75);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgba(255, 0, 0, 0.95);\n"
"            }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_18.addWidget(self.pushButton_2)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(4, 1)
        self.horizontalLayout_18.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_13)
        self.horizontalFrame_14 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.horizontalFrame_14.setMaximumSize(QtCore.QSize(16777215, 52))
        self.horizontalFrame_14.setStyleSheet("border-radius: 9px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_14.setObjectName("horizontalFrame_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalFrame_14)
        self.horizontalLayout_19.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(parent=self.horizontalFrame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.RuleName_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.RuleName_lineEdit_3.setFont(font)
        self.RuleName_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.RuleName_lineEdit_3.setObjectName("RuleName_lineEdit_3")
        self.horizontalLayout_19.addWidget(self.RuleName_lineEdit_3)
        self.label_23 = QtWidgets.QLabel(parent=self.horizontalFrame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.KeyWord_comboBox_3 = QtWidgets.QComboBox(parent=self.horizontalFrame_14)
        self.KeyWord_comboBox_3.setMinimumSize(QtCore.QSize(76, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KeyWord_comboBox_3.setFont(font)
        self.KeyWord_comboBox_3.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.KeyWord_comboBox_3.setObjectName("KeyWord_comboBox_3")
        self.KeyWord_comboBox_3.addItem("")
        self.KeyWord_comboBox_3.addItem("")
        self.horizontalLayout_19.addWidget(self.KeyWord_comboBox_3)
        self.KeyWord_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_14)
        self.KeyWord_lineEdit_3.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit_3.setFont(font)
        self.KeyWord_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit_3.setObjectName("KeyWord_lineEdit_3")
        self.horizontalLayout_19.addWidget(self.KeyWord_lineEdit_3)
        self.label_24 = QtWidgets.QLabel(parent=self.horizontalFrame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.Reply_lineEdit_3 = QtWidgets.QLineEdit(parent=self.horizontalFrame_14)
        self.Reply_lineEdit_3.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit_3.setFont(font)
        self.Reply_lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit_3.setObjectName("Reply_lineEdit_3")
        self.horizontalLayout_19.addWidget(self.Reply_lineEdit_3)
        self.file_pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalFrame_14)
        self.file_pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton_3.setText("")
        icon = QtGui.QIcon.fromTheme(get_resource_path("resources/img/page1/page1_打开文件.svg"))
        self.file_pushButton_3.setIcon(icon)
        self.file_pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton_3.setObjectName("file_pushButton_3")
        self.horizontalLayout_19.addWidget(self.file_pushButton_3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalFrame_14)
        self.pushButton_3.setMinimumSize(QtCore.QSize(42, 24))
        self.pushButton_3.setMaximumSize(QtCore.QSize(42, 24))
        self.pushButton_3.setStyleSheet("            QPushButton {\n"
"                background-color: rgba(255, 0, 0, 0.55);\n"
"                border: none;\n"
"                border-radius: 4px;\n"
"                color: white;\n"
"                font-size: 12px;\n"
"                padding: 2px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 0, 0, 0.75);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgba(255, 0, 0, 0.95);\n"
"            }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_19.addWidget(self.pushButton_3)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(4, 1)
        self.horizontalLayout_19.setStretch(6, 1)
        self.verticalLayout_3.addWidget(self.horizontalFrame_14)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_download = QtWidgets.QPushButton(parent=self.mainframe)
        self.pushButton_download.setMinimumSize(QtCore.QSize(88, 36))
        self.pushButton_download.setMaximumSize(QtCore.QSize(88, 36))
        self.pushButton_download.setStyleSheet("QPushButton {\n"
"    background-color: rgba(105, 27, 253, 180);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(105, 27, 253, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 27, 253, 250);\n"
"}")
        self.pushButton_download.setObjectName("pushButton_download")
        self.horizontalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.mainframe)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.setStretch(0, 5)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_6.setStretch(0, 9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ReplyDialog)
        QtCore.QMetaObject.connectSlotsByName(ReplyDialog)

    def retranslateUi(self, ReplyDialog):
        _translate = QtCore.QCoreApplication.translate
        ReplyDialog.setWindowTitle(_translate("ReplyDialog", "Dialog"))
        self.label_title.setText(_translate("ReplyDialog", "自动回复规则"))
        self.label_16.setText(_translate("ReplyDialog", "名称"))
        self.RuleName_lineEdit_1.setPlaceholderText(_translate("ReplyDialog", "输入名称"))
        self.label_17.setText(_translate("ReplyDialog", "关键词"))
        self.KeyWord_comboBox_1.setItemText(0, _translate("ReplyDialog", "半匹配"))
        self.KeyWord_comboBox_1.setItemText(1, _translate("ReplyDialog", "全匹配"))
        self.KeyWord_lineEdit_1.setPlaceholderText(_translate("ReplyDialog", "输入关键词"))
        self.label_18.setText(_translate("ReplyDialog", "回复内容"))
        self.Reply_lineEdit_1.setPlaceholderText(_translate("ReplyDialog", "文字或文件路径"))
        self.pushButton_1.setText(_translate("ReplyDialog", "清空"))
        self.label_19.setText(_translate("ReplyDialog", "名称"))
        self.RuleName_lineEdit_2.setPlaceholderText(_translate("ReplyDialog", "输入名称"))
        self.label_20.setText(_translate("ReplyDialog", "关键词"))
        self.KeyWord_comboBox_2.setItemText(0, _translate("ReplyDialog", "半匹配"))
        self.KeyWord_comboBox_2.setItemText(1, _translate("ReplyDialog", "全匹配"))
        self.KeyWord_lineEdit_2.setPlaceholderText(_translate("ReplyDialog", "输入关键词"))
        self.label_21.setText(_translate("ReplyDialog", "回复内容"))
        self.Reply_lineEdit_2.setPlaceholderText(_translate("ReplyDialog", "文字或文件路径"))
        self.pushButton_2.setText(_translate("ReplyDialog", "清空"))
        self.label_22.setText(_translate("ReplyDialog", "名称"))
        self.RuleName_lineEdit_3.setPlaceholderText(_translate("ReplyDialog", "输入名称"))
        self.label_23.setText(_translate("ReplyDialog", "关键词"))
        self.KeyWord_comboBox_3.setItemText(0, _translate("ReplyDialog", "半匹配"))
        self.KeyWord_comboBox_3.setItemText(1, _translate("ReplyDialog", "全匹配"))
        self.KeyWord_lineEdit_3.setPlaceholderText(_translate("ReplyDialog", "输入关键词"))
        self.label_24.setText(_translate("ReplyDialog", "回复内容"))
        self.Reply_lineEdit_3.setPlaceholderText(_translate("ReplyDialog", "文字或文件路径"))
        self.pushButton_3.setText(_translate("ReplyDialog", "清空"))
        self.pushButton_download.setText(_translate("ReplyDialog", "保存"))
